[project]
site_name = "Cheat Sheets"
repo_name = "ivansaul/cheat-sheets"
repo_url = "https://github.com/ivansaul/cheat-sheets"
site_description = "Your all-in-one developer reference for Python, JavaScript, Docker, Git, DevOps, and more."
site_author = "ivansaul"
site_url = "https://cheatsheet-docs.pages.dev/"
copyright = "Copyright &copy; 2026 @ivansaul"

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "fontawesome/solid/layer-group"
repo = "fontawesome/brands/git-alt"

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ivansaul/cheat-sheets"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/tDvybtJ7y9"
